spring:
  application:
    name: ai-study-assistant

  ai:
    openai:
      api-key: ${GROQ_API_KEY}
      base-url: https://api.groq.com/openai
      chat:
        options:
          model: llama-3.3-70b-versatile
          temperature: 0.6
          max-tokens: 3000

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

server:
  port: ${PORT:8080}

logging:
  level:
    com.study: INFO
    org.springframework.ai: DEBUG